name: Publishes new version of the library

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'

    - run: npm ci
    
    - run: npm run build

    - name: Get package.json version
      id: package
      run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
  
    - name: Create release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/*
        file_glob: true
        tag: v${{steps.package.outputs.version}}
        release_name: ${{ steps.package.outputs.version }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
